# Generated by Django 4.1 on 2022-08-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_name',
            field=models.CharField(default='Author name', max_length=255),
            preserve_default=False,
        ),
    ]
